"""Test Case: Valid login grants access to appointments
Scenario: bcda40e9-e5ab-47b9-b3d6-1721ab986d92 | Test Case ID: 54d379e3-a995-4282-8f3c-806b628be573
Generated by Test Case Generation Platform.
"""
import pytest
from playwright.sync_api import Page, expect
from modules.core.pages.home_page import HomePage
from modules.dashboard.pages.dashboard_page import DashboardPage
from modules.terms_and_conditions.pages.terms_and_conditions_page import TermsAndConditionsPage
from modules.privacy_policy.pages.privacy_policy_page import PrivacyPolicyPage
from modules.appointments.pages.appointments_page import AppointmentsPage
from modules.caregivers.pages.caregivers_page import CaregiversPage
from modules.participants.pages.participants_page import ParticipantsPage

@pytest.mark.regression
def test_valid_login_grants_access_to_appointments(page: Page, default_credentials: dict) -> None:
    """Valid login grants access to appointments."""
    home_page = HomePage(page)
    dashboard_page = DashboardPage(page)
    terms_and_conditions_page = TermsAndConditionsPage(page)
    privacy_policy_page = PrivacyPolicyPage(page)
    appointments_page = AppointmentsPage(page)
    caregivers_page = CaregiversPage(page)
    participants_page = ParticipantsPage(page)

    # Step 1: Navigate to base application
    home_page.navigate()
    home_page.assert_loaded()

    # Step 1: Navigate to the login page
    if hasattr(home_page, 'fill_user_name'):
        home_page.fill_user_name(default_credentials['username'])
    if hasattr(home_page, 'fill_password'):
        home_page.fill_password(default_credentials['password'])
    if hasattr(home_page, 'click_login_button'):
        home_page.click_login_button()

    # Step 2: Fill "Username" with "scheduler_user"
    if hasattr(home_page, 'fill_user_name'):
        home_page.fill_user_name(default_credentials['username'])
    if hasattr(home_page, 'fill_password'):
        home_page.fill_password(default_credentials['password'])
    if hasattr(home_page, 'click_login_button'):
        home_page.click_login_button()

    # Step 3: Fill "Password" with "Password123!"

    # Step 4: Click "Login" button
    if hasattr(home_page, 'fill_user_name'):
        home_page.fill_user_name(default_credentials['username'])
    if hasattr(home_page, 'fill_password'):
        home_page.fill_password(default_credentials['password'])
    if hasattr(home_page, 'click_login_button'):
        home_page.click_login_button()

    # Step 5: Verify that the appointments dashboard is displayed
