"""Test Case: Auto‑renewed appointment retains caregiver when travel time is sufficient
Scenario: 71b5157a-5ce0-43b7-9b16-7ac86e0938a1 | Test Case ID: 73b167d6-e11b-4dcf-b116-58e822ba5f4b
Generated by Test Case Generation Platform.
"""
import pytest
from playwright.sync_api import Page, expect
from modules.core.pages.home_page import HomePage
from modules.dashboard.pages.dashboard_page import DashboardPage
from modules.terms_and_conditions.pages.terms_and_conditions_page import TermsAndConditionsPage
from modules.privacy_policy.pages.privacy_policy_page import PrivacyPolicyPage
from modules.appointments.pages.appointments_page import AppointmentsPage
from modules.caregivers.pages.caregivers_page import CaregiversPage
from modules.participants.pages.participants_page import ParticipantsPage

@pytest.mark.regression
def test_autorenewed_appointment_retains_caregiver_when_travel_time_is_sufficient(page: Page, default_credentials: dict) -> None:
    """Auto‑renewed appointment retains caregiver when travel time is sufficient."""
    home_page = HomePage(page)
    dashboard_page = DashboardPage(page)
    terms_and_conditions_page = TermsAndConditionsPage(page)
    privacy_policy_page = PrivacyPolicyPage(page)
    appointments_page = AppointmentsPage(page)
    caregivers_page = CaregiversPage(page)
    participants_page = ParticipantsPage(page)

    # Step 1: Navigate to base application
    home_page.navigate()
    home_page.assert_loaded()

    # Step 1: Navigate to the appointments dashboard

    # Step 2: Locate appointment with caregiver "John Doe" and travel time "45 minutes"

    # Step 3: Click "Auto-Renew" button for the appointment

    # Step 4: Verify caregiver "John Doe" remains assigned

    # Step 5: Verify no "Caregiver Conflict" indicator is displayed
